import Head from "next/head";
import Link from "next/link";

import {
  BindToViewPort,
  BTVP_BottomSection,
} from "../components/app/BindToviewPort";
import NavBar from "../components/app/NavBar";
import Footer from "../components/app/Footer";

import "../styles/_app.scss";

import type { AppProps } from "next/app";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Cascade</title>

        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div
        style={{
          top: 0,
          left: 0,
          transform: "translate(-50%, -50%)",
        }}
        className='artBox'
      />
      <div
        style={{ right: 0, bottom: 0, transform: "translate(50%, 50%)" }}
        className='artBox'
      />

      <BindToViewPort>
        <Component {...pageProps} />

        <BTVP_BottomSection>
          <NavBar>
            <Link href='/'>Home</Link>
            <Link href='/contact'>Contact Us</Link>
            <Link href='/services'>Services</Link>
            <Link href='/projects'>Projects</Link>
          </NavBar>
          <Footer />
        </BTVP_BottomSection>
      </BindToViewPort>
    </>
  );
}
