import Head from "next/head";
import Link from "next/link";

import NavBar from "../components/app/NavBar";
import Footer from "../components/app/Footer";
import FixedContainer from "../components/utility/FixedContainer";

import "../styles/_app.scss";

import type { AppProps } from "next/app";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Cascade</title>

        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div
        className='artBox'
        style={{
          top: 0,
          left: 0,
          transform: "translate(-50%, -50%)",
        }}
      />
      <div
        className='artBox'
        style={{ right: 0, bottom: 0, transform: "translate(50%, 50%)" }}
      />

      <main>
        <Component {...pageProps} />
      </main>

      <FixedContainer
        style={{
          left: 0,
          bottom: 0,
          zIndex: 900,
          width: "100vw",
          background: "var(--primary-background-color)",
        }}
      >
        <NavBar>
          <Link href='/'>Home</Link>
          <Link href='/contact'>Contact Us</Link>
          <Link href='/services'>Services</Link>
          <Link href='/projects'>Projects</Link>
        </NavBar>
        <Footer />
      </FixedContainer>
    </>
  );
}
