import Head from "next/head";
import BindToViewPort from "../components/app/BindToviewPort";

import styles from "../styles/index.module.scss";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Cascade</title>

        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>

      <BindToViewPort>
        <h1>Cascade</h1>
      </BindToViewPort>

      <footer className={styles.footer}></footer>
    </>
  );
}
