import Head from "next/head";
import Footer from "../components/app/Footer";

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>Cascade</title>

        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <label>Services Page</label>
      </main>

      <Footer />
    </>
  );
}
